---
- name: Run command apt-get update && apt-get upgrade for Ubuntu
  hosts: odroid
  gather_facts: False
  pre_tasks:
    - name: Install Minimal Python For Ansible
      raw: test -e /usr/bin/python || (apt update && apt install -y python-minimal)
      register: test
      changed_when: test.stdout

  tasks:
    - name: Add the user 'vrc' with a bash shell, appending the group 'sudo' to the user's groups  
      user:
        name: vrc
        password: odroid
        shell: /bin/bash
        groups: sudo

    - name: Set authorized key for user vrc copying it from current user
      authorized_key:
        user: vrc
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes    
        cache_valid_time: 3600

    - name: Install list of packages
      apt: 
        name:
        - mc
        - screen
        - tmux
        - htop
        - git 
        - automake 
        - autoconf 
        - pkg-config 
        - libcurl4-openssl-dev 
        - libjansson-dev 
        - libssl-dev 
        - libgmp-dev
        - zlib1g-dev
        state: present   

    - name: Remove a module ads7846
      command: modprobe -r ads7846

    - name: Prevents the kernel module ads7846 from being loaded after reboot
      command: tee /etc/modprobe.d/blacklist-ads7846.conf <<< "ads7846"       

    - name: Clone and update git veriumMiner repository 
      become: true
      become_user: vrc 
      git:
        repo: 'https://github.com/fireworm71/veriumMiner'
        dest: /home/vrc/veriumMiner
        clone: yes
        update: yes
