---
- name: Run script vrmcheck.sh
  hosts: odroid
  gather_facts: no

  
  tasks:
    - name: This command will run shell script on remote hosts and show log.
      shell: "./vrmcheck.sh"
      register: shell_result

    - debug:
        var: shell_result.stdout_lines
